### PR TITLE
Value-parser and filter fallback

### PR DESCRIPTION
**Pull request by TrySound**
Hi, @magsout ! My value-parser done. It's more safe then regexp.

### CODE REVIEW

**Comment by MoOx** [comment]
Why did you close this one? It sounds better than a brutal #22 :/

**Comment by TrySound** [comment]
@MoOx He added filter feature. Let's just wait he fix all comments. But do not delete my branch.

**Comment by MoOx** [comment]
There is already #18 for the legacy filter.

**Comment by TrySound** [comment]
Okay

**Comment by magsout** [comment]
sorry for my lateeeee review. Thanks for your job @TrySound

**Pull request merged**
