### PR TITLE
Whitelist selectors and Fixed fallback

### LINKED ISSUE #10: no rgba-fallback for box-shadow
According to caniuse, `rgba` is supported in the same (and more) browsers than `box-shadow`. Thus there's no fallback needed there.

Sure, there are other properties like `text-stroke` or `text-decoration-color` and functions like `linear-gradient`, too.
It would be great to have the possibility to define the properties/functions for that we want/don't want to have a fallback.

For now, only `color`, `background-color`, `border-color`, and `outline-color` comes into my mind (thus, whitelisting should be sufficient)...

### LINKED ISSUE #11: Should not add fallback when there is already one, even named colors, or rgb()
Following test

```css
.test1 {
    background-color: #fff;
    background-color: rgba(0, 0, 0, 0.5);
}

.test2 {
    background-color: orange;
    background-color: rgba(0, 0, 0, 0.5);
}

.test3 {
    background-color: rgb(128, 128, 128);
    background-color: rgba(0, 0, 0, 0.5);
}
```

leads to
```css

.test1 {
    background-color: #fff;
    background-color: rgba(0, 0, 0, 0.5);
}

.test2 {
    background-color: orange;
    background-color: #000000;
    background-color: rgba(0, 0, 0, 0.5);
}

.test3 {
    background-color: rgb(128, 128, 128);
    background-color: #000000;
    background-color: rgba(0, 0, 0, 0.5);
}
```

- :white_check_mark: `.test1` works 
- :bug: `.test2`
  named colors aren't recognized
- :bug: `.test3`
  One can argue that [there's a bug in IE6 & 7 with rgb()](https://css-tricks.com/ie-background-rgb-bug/), but even then, you should use the values from `rgb()`, not `rgba()`. So it should be `#808080` - and it should be before or insted of `rgb()`.

Edit: I removed two test cases with the `color`-function (from `postcss-color-function`) - they are redundant-

### PR DESCRIPTION
**Pull request by magsout**
Close #10  and Close #11

### CODE REVIEW

**Comment by TrySound** [comment]
@magsout I think `selectors` will confuse users. Better `properties` or `whitelist`.

**Comment by TrySound** [comment]
@magsout Are you sure, using `const` in es5 is the good way?

**Comment by magsout** [comment]
>@magsout I think selectors will confuse users. Better properties or whitelist.

@TrySound Yes, properties maybe, but not whitelist

**Comment by magsout** [comment]
>@magsout Are you sure, using const in es5 is the good way?

Ah ah , my fault, I love using `const`... More semantics.. Not very important, I can write var

**Comment by magsout** [comment]
done @TrySound

**Comment by TrySound** [comment]
@magsout  I like it now.

**Comment by MoOx** [comment]
lgtm

**Comment by magsout** [comment]
thanks for the review

**Pull request merged**
